#--Run this on your AUTH database

ALTER TABLE account 
ADD	
	donator TINYINT(4) NOT NULL DEFAULT '0',
	rank INT(32) NULL DEFAULT NULL,
	staff_id INT(32) NULL DEFAULT NULL,
	vp VARCHAR(50) NULL DEFAULT '0',
	dp VARCHAR(50) NULL DEFAULT '0',
	isactive INT(32) NULL DEFAULT NULL,
	activation VARCHAR(255) NULL DEFAULT NULL,
	VipLevel TINYINT(4) NOT NULL DEFAULT '0',
	total_votes INT(11) NOT NULL DEFAULT '0',
	country VARCHAR(255) NULL DEFAULT NULL,
	age VARCHAR(255) NULL DEFAULT NULL,
	foundus VARCHAR(255) NULL DEFAULT NULL,
	avatar VARCHAR(255) NOT NULL DEFAULT 'images/avatars/darksoke.png',
	CustomRank VARCHAR(50) NOT NULL DEFAULT 'Member';
